### ISSUE TITLE
Duplicate type in schema and datamodel in order to limit access to limit access to specific field

### ISSUE THREAD

**Issue by alan345** [LawJolla/prisma-auth0-example#12]
Thanks for your repo, it is really helpfull!

What if we want to limit access to limit access to specific field?
![image](https://user-images.githubusercontent.com/15246526/50606125-721f5b00-0e79-11e9-9013-59530c6b197f.png)
https://www.prisma.io/blog/graphql-directive-permissions-authorization-made-easy-54c076b5368e

You declare type User in 2 files:
 1. your `datamodel.graphql`

https://github.com/LawJolla/prisma-auth0-example/blob/master/server/database/datamodel.graphql#L15-L24

```
type User {
  id: ID! @unique
  email: String @unique
  role: Role @default(value: CUSTOMER)
  name: String
  avatar: String
  auth0id: String! @unique
  identity: String
  posts: [Post!]! @relation(name: "UserPosts")
}
```

2. in `schema.graphql`

https://github.com/LawJolla/prisma-auth0-example/blob/master/server/src/schema.graphql#L22-L30

```
type User {
  id: ID!
  email: String @isOwner(type: "User")
  role: Role
  name: String
  avatar: String
  identity: String
  posts: [Post!]!
}
```

There is no way to avoid duplicate and add directives in 1 file only (maybe `schema.graphql` only?)

Thanks for your answer

**Comment by LawJolla** [comment]
Hi @alan345,

Thanks for your question!

There are a few ways to answer this question, so if it doesn't make sense, please let me know and I'll attack it another way.

There are two GraphQL servers in this repo - the GraphQL Yoga instance and Prisma.  All requests hit the Yoga server.  Then, depending on the resolver in the Yoga server, it may query Prisma for additional data.

--- request -->Yoga (schema.graphql) --<maybe> --> Prisma (datamodel.graphql) --> Database

You can think of `datamodel.graphql` as your database schema.  You'll notice that there are fields that exist on `datamodel.graphql` that aren't on `schema.graphql.`  For instance, users don't need to query their `auth0id`.  That's why the two schemas are different.

To your specific question, the directives give different servers different information.  For `datamodel`, `@unique` tells Prisma that the field must be unique.  Prisma then migrates the database to enforce that constraint.  `@isOwner` tells Yoga to look for a directive resolver and run the associated function.

Combining the two wouldn't make sense.  Prisma doesn't have a permissions layer (they intentionally leave that up to the application server), so it doesn't have any permission directives like `@isOwner`.  Likewise, `@unique` on `schema.graphql` doesn't make sense because that schema/server doesn't enforce data layer restrictions.

Hopefully that helped!

**Comment by alan345** [comment]
Hi @LawJolla 
Thanks very much for the explanation. It is very clear. 
I will do more testing to figure out the behavior when there are discrepancies between `Yoga (schema.graphql)` and `Prisma (datamodel.graphql)` as I am a bit concerned about maintenance on a long run.


Last question, if I had a directive on the filed level, like:

```
#schema.graphql
type Product {
  id: ID!
  urlName: String!
  owners: [User!]! @isAuthenticated
}
```

if the user is not authenticated, the whole query returns an error; not just the field.
![image](https://user-images.githubusercontent.com/15246526/50670696-2b695800-0f82-11e9-86fa-10c42a086972.png)

Is it the expected behavior?

Thanks again

**Comment by alan345** [comment]
for my last question, I just return `[]` when not admin and next() if admin. It is doing the job
Thanks again for your help

```
const directiveResolvers = {
  isAuthenticated: async (next, source, args, ctx) => {
    let userId = ''
    try {
      userId = await utils.getUserId(ctx)
    } catch (e) {
      return []
    }
    return next()
  },
}
```

**Comment by LawJolla** [comment]
Error handling is still a little unsettled in GraphQL land.  The normal way to do it is pass whatever data returns on the `data` property and errors on the `errors` property.  

The reason your query returns `product: null` is `owners` cannot be null.  If you allow owners to be null, you'll get the data returned with the error.

Or, as you've done, returning an empty array works too.  (And many computer science people argue that an empty array should be used in place of null for lists everywhere, so there you go. :) )

**Comment by alan345** [comment]
Hello!
Another question. 
I am trying to add an authentication directive on the model level: To give access to object `Order` only for admin and Owners.
in file `shcema.graphql`
```
directive @auth(requires: Role = ADMIN) on OBJECT 

type Order @auth(requires: ADMIN) {
  id: ID!
  price: Float!
}
```
I am using directive type `on OBJECT` as explained here: https://www.apollographql.com/docs/graphql-tools/schema-directives.html#Enforcing-access-permissions but I need to implement the `visitObject` method

![image](https://user-images.githubusercontent.com/15246526/50746082-3cb09f80-11e2-11e9-998c-1dff9d0bbea8.png)

Any idea where to implement this function in your stack (the apollographql documentation suggest to create a class `SchemaDirectiveVisitor`)?
Also, FYI, they will deprecate `directiveResolvers` (https://www.apollographql.com/docs/graphql-tools/schema-directives.html#What-about-directiveResolvers)

Thanks

**Comment by LawJolla** [comment]
I'm not sure because I haven't had time to work with the new API.  Sorry about that. 

The linked page said the opposite of what you said.  ". . .we have no immediate plans to deprecate directiveResolvers"
