### ISSUE TITLE
Passing incoming argument to directive

### ISSUE THREAD

**Issue by ahmadsn26** [LawJolla/prisma-auth0-example#7]
Hi...

it was nice reading this article i am wondering if its possible to pass the argument that we receive in either query or mutation to directive

for example in here

`post(id: ID!): Post @isOwnerOrHasRole(type: "Post", roles: ["ADMIN"])`

if i want to post id to my function any idea how would i do it .... sorry i am a bit new to directives so i am unable to figure out if its possible

**Comment by LawJolla** [comment]
Hi @ahmadsn26 !

Thanks for your question.  I'm not sure what you're trying to do.  Do you want the Post's id in your resolver?

**Comment by ahmadsn26** [comment]
Yes that is excatly what i am looking for..

**Comment by LawJolla** [comment]
@ahmadsn26 ,

You'll want a fragment.  Take a look at my post here:  http://www.graph.cool/forum/t/prisma-auth0-directive-permissions-example/2313/9  and read the other posts from Jordan.  That should give you a clear picture.

GraphQL-Tools was also updated since I last updated the repo to include `Schema Directives` that probably provides a more elegant solution than fragments and directive resolvers.  (I haven't had the time to dig into them) Directive resolvers aren't deprecated, but they are on their way out.

https://www.apollographql.com/docs/graphql-tools/schema-directives.html

If you learn of a more elegant way, please report back!

**Comment by ahmadsn26** [comment]
i achieved it with graphql-tools simply define your schemaDirectives

`const executableSchema = makeExecutableSchema({
  typeDefs: YourTypeDefs,
  resolvers,
  schemaDirectives: {
    directiveResolverName: MyResolver 
  }
});`


and the resolver will have object with all the info


```
import { defaultFieldResolver } from 'graphql';
import { SchemaDirectiveVisitor } from 'graphql-tools';

class MyResolver extends SchemaDirectiveVisitor {
  visitFieldDefinition(field) {
    const { resolve = defaultFieldResolver } = field;

    field.resolve = function (...args) {
      // in here args[1] -> args[n] will have everything like headers/context/body etc and you can play 
      //around with it. if the condition you want is matched just simply do the next line
       return resolve.apply(this, args);

     // so for example 
    // if(!condition){
               throw Error("YOUR_ERROR");
        }else{
              return resolve.apply(this, args);
         }
    }
  }
}

module.exports.MyResolver = MyResolver;
```

might help someone using serverless environment 

 Will close this and Thank you @LawJolla  for the directions actually graphql-tool way is pretty neat to handle this
